### PR TITLE
Use native linking on Arch linux.

### PR DESCRIPTION
**Pull request by yglukhov**
Apparently there's a problem linking with librocksdb on Arch linux with default nim glue linking.
Related issues:
https://github.com/jemalloc/jemalloc/issues/955, https://github.com/jemalloc/jemalloc/issues/937
<details> 
  <summary>Another problem noticed:</summary>
<pre>
$ nimbus
     19813:
     19813:     WARNING: Unsupported flag value(s) of 0x8000000 in DT_FLAGS_1.
     19813:
     19813:     file=libm.so.6 [0];  needed by nimbus [0]
     19813:     file=libm.so.6 [0];  generating link map
     19813:       dynamic: 0x00006584b901ec90  base: 0x00006584b8e9b000   size: 0x0000000000184018
     19813:         entry: 0x00006584b8ea8020  phdr: 0x00006584b8e9b040  phnum:                 10
     19813:
     19813:
     19813:     file=librt.so.1 [0];  needed by nimbus [0]
     19813:     file=librt.so.1 [0];  generating link map
     19813:       dynamic: 0x00006584b8e99bf0  base: 0x00006584b8e91000   size: 0x00000000000099f8
     19813:         entry: 0x00006584b8e93020  phdr: 0x00006584b8e91040  phnum:                 10
     19813:
     19813:
     19813:     file=libdl.so.2 [0];  needed by nimbus [0]
     19813:     file=libdl.so.2 [0];  generating link map
     19813:       dynamic: 0x00006584b8e8fd30  base: 0x00006584b8e8c000   size: 0x0000000000004090
     19813:         entry: 0x00006584b8e8d020  phdr: 0x00006584b8e8c040  phnum:                 10
     19813:
     19813:
     19813:     file=libc.so.6 [0];  needed by nimbus [0]
     19813:     file=libc.so.6 [0];  generating link map
     19813:       dynamic: 0x00006584b8e859e0  base: 0x00006584b8cc8000   size: 0x00000000001c3640
     19813:         entry: 0x00006584b8cec330  phdr: 0x00006584b8cc8040  phnum:                 13
     19813:
     19813:
     19813:     file=libpthread.so.0 [0];  needed by /usr/lib/librt.so.1 [0]
     19813:     file=libpthread.so.0 [0];  generating link map
     19813:       dynamic: 0x00006584b8cc2ae0  base: 0x00006584b8ca7000   size: 0x00000000000201c8
     19813:         entry: 0x00006584b8cad6e0  phdr: 0x00006584b8ca7040  phnum:                 12
     19813:
     19813:
     19813:     calling init: /usr/lib/libpthread.so.0
     19813:
     19813:
     19813:     calling init: /usr/lib/libc.so.6
     19813:
     19813:
     19813:     calling init: /usr/lib/libdl.so.2
     19813:
     19813:
     19813:     calling init: /usr/lib/librt.so.1
     19813:
     19813:
     19813:     calling init: /usr/lib/libm.so.6
     19813:
     19813:
     19813:     initialize program: nimbus
     19813:
     19813:
     19813:     transferring control: nimbus
     19813:
     19813:
     19813:     file=librocksdb.so [0];  dynamically loaded by nimbus [0]
     19813:     file=librocksdb.so [0];  generating link map
     19813:       dynamic: 0x00006584b8c0d628  base: 0x00006584b85b5000   size: 0x000000000066e548
     19813:         entry: 0x00006584b86ce020  phdr: 0x00006584b85b5040  phnum:                 10
     19813:
     19813:
     19813:     file=libsnappy.so.1 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libsnappy.so.1 [0];  generating link map
     19813:       dynamic: 0x00006584b85b3cc8  base: 0x00006584b83ad000   size: 0x0000000000207018
     19813:         entry: 0x00006584b83af3e0  phdr: 0x00006584b83ad040  phnum:                  7
     19813:
     19813:
     19813:     file=libz.so.1 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libz.so.1 [0];  generating link map
     19813:       dynamic: 0x00006584b83abc90  base: 0x00006584b8196000   size: 0x0000000000216010
     19813:         entry: 0x00006584b81981d0  phdr: 0x00006584b8196040  phnum:                  7
     19813:
     19813:
     19813:     file=libbz2.so.1.0 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libbz2.so.1.0 [0];  generating link map
     19813:       dynamic: 0x00006584b8194ce0  base: 0x00006584b8183000   size: 0x0000000000012c48
     19813:         entry: 0x00006584b8185020  phdr: 0x00006584b8183040  phnum:                  9
     19813:
     19813:
     19813:     file=liblz4.so.1 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=liblz4.so.1 [0];  generating link map
     19813:       dynamic: 0x00006584b8181cc8  base: 0x00006584b8164000   size: 0x000000000001e010
     19813:         entry: 0x00006584b8166020  phdr: 0x00006584b8164040  phnum:                  9
     19813:
     19813:
     19813:     file=libzstd.so.1 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libzstd.so.1 [0];  generating link map
     19813:       dynamic: 0x00006584b8162a58  base: 0x00006584b7ecc000   size: 0x0000000000297038
     19813:         entry: 0x00006584b7ed05b0  phdr: 0x00006584b7ecc040  phnum:                  7
     19813:
     19813:
     19813:     file=libtbb.so.2 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libtbb.so.2 [0];  generating link map
     19813:       dynamic: 0x00006584b7ec67d0  base: 0x00006584b7e8a000   size: 0x0000000000041340
     19813:         entry: 0x00006584b7e99020  phdr: 0x00006584b7e8a040  phnum:                  9
     19813:
     19813:
     19813:     file=libjemalloc.so.2 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libjemalloc.so.2 [0];  generating link map
     19813:       dynamic: 0x00006584b7c79b78  base: 0x00006584b79f7000   size: 0x0000000000492278
     19813:         entry: 0x00006584b79fc870  phdr: 0x00006584b79f7040  phnum:                  8
     19813:
     19813:
     19813:     file=libstdc++.so.6 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libstdc++.so.6 [0];  generating link map
     19813:       dynamic: 0x00006584b79f03a8  base: 0x00006584b7868000   size: 0x000000000018e640
     19813:         entry: 0x00006584b78f1020  phdr: 0x00006584b7868040  phnum:                 11
     19813:
     19813:
     19813:     file=libgcc_s.so.1 [0];  needed by /usr/lib/librocksdb.so [0]
     19813:     file=libgcc_s.so.1 [0];  generating link map
     19813:       dynamic: 0x00006584b7866cd0  base: 0x00006584b784e000   size: 0x00000000000192f0
     19813:         entry: 0x00006584b7851020  phdr: 0x00006584b784e040  phnum:                 10
     19813:
     19813:
     19813:     file=/usr/lib/librocksdb.so [0];  needed by /usr/lib/libstdc++.so.6 [0] (relocation dependency)
     19813:
     19813:
     19813:     file=librocksdb_lite.so [0];  dynamically loaded by nimbus [0]
could not load: librocksdb(|_lite).so
compile with -d:nimDebugDlOpen for more information
</pre>
</details>

### CODE REVIEW

**Review by zah — APPROVED** [review]

**Comment by arnetheduck** [comment]
oops, missed this - why not always native-link instead? seems like a bother to support special arch stuff that doesn't get testing

**Comment by yglukhov** [comment]
@arnetheduck, don't worry, that's tested, arch is my primary platform :). I don't know how all linuxes work, but I know some of them provide both `*-dev` and non-dev version of the package, nim glueing usually  allows to not install the `*-dev` version, kinda more chances to work out of the box. That said I don't mind too much native linking for all... linuxes?

**Comment by arnetheduck** [comment]
well, for simplicity I'd go with the same style of linking for all platforms - the fewer moving parts, the better in my world - not sure if it's feasible though.

As far as package support goes, rocksdb is a bit non-standard - different distros and even different arches of the same distro either provide it or not (ie debian does not provide it on arm, but does on x86), and with different compile options (snappy compression support etc). it's a mess.

at some point, perhaps we really should lock down rocksdb more tightly and build it statically as part of the build, at least for nimbus.

**Comment by stefantalpalaru** [comment]
I'm seeing the same dlopen() error on Gentoo ~amd64, with rocksdb-5.15.10 linked to jemalloc-5.1.0.

**Pull request merged**
