### PR TITLE
Removed header dependency

### PR DESCRIPTION
**Pull request by yglukhov**
Since all structs are opaque anyway

### CODE REVIEW

**Review by mratsim — APPROVED** [review]

**Comment by arnetheduck** [comment]
shouldn't these be `{.incompleteStruct.}` then?

**Comment by cheatfate** [comment]
What happens if this objects will become parts of other objects, how can compiler know size of this objects?

**Comment by arnetheduck** [comment]
my guess is that only pointers to these structs are used throughout - `incompleteStruct` should catch any other uses and give a compile error, to ensure that they're not used the wrong way / that the compiler is blocked from using their empty size

**Comment by yglukhov** [comment]
Addressed: https://github.com/status-im/nim-rocksdb/pull/8

**Pull request merged**
