### PR TITLE
use dynamic linking instead of dlopen on all Linux distros

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by arnetheduck** [comment]
why does this help / why would the `.so` lookup be different compared to `dlopen`?

**Review by mratsim — COMMENTED** [review]
AFAIK the way to avoid dlopen is to remove all `dynlib` pragma and place a `{.link: "path/to/.so".}` somewhere.

Here is how I wrapped a C++ library without dlopen last weekend as I had an issue with dlopen and C++ name mangling:

https://github.com/numforge/agent-smith/blob/a2d9251e289f92f6b5fb68e19a98d16b00f2694c/third_party/ale_wrap.nim#L36

You can notice that in the file there is no `dynlib` at all.

**Comment by arnetheduck** [comment]
why I'm asking is because there's generally no difference in lookup between `.so` being linked natively or through dlopen, as far as lookup paths go - unless you also sprinkle with `rpath`'s - thus I'm curious to hear why this approach solves that problem.

one thing I've been considering more and more lately is that we suspend rocksdb support for now and go with sqlite or whatever, then revisit rocksdb when we're closer to a working product and we start feeling that sqlite is limiting. this way, we can move faster with fewer distractions while we develop the core logic, across the board. sqlite is incredibly more easy to build, and we can link it statically.

@zah @yglukhov thoughts?

finally, just to be clear, I'm not a fan of Nim's `dlopen` approach - it's a ticking bomb to dll hell in general.

**Comment by stefantalpalaru** [comment]
> why does this help / why would the `.so` lookup be different compared to `dlopen`?

In this particular case, it's an incompatibility between new versions of jemalloc (RocksDB links to it) and dlopen: https://github.com/jemalloc/jemalloc/issues/1237

> AFAIK the way to avoid dlopen is to remove all dynlib pragma and place a {.link: "path/to/.so".} somewhere.

Here it's handled with a custom pragma:
```nim
when shouldUseNativeLinking():
  {.pragma: importrocks, importc, cdecl.}
  {.passL: "-lrocksdb".}
else:
  {.pragma: importrocks, importc, cdecl, dynlib: librocksdb.}
```

**Comment by arnetheduck** [comment]
oh, ok, I thought this solved some other issue - and that only arch was affected due to how it links jemalloc..

**Comment by stefantalpalaru** [comment]
> due to how it links jemalloc

Just a matter of jemalloc version. Upstream's workaround is a configuration option that does not sound encouraging:

> --disable-initial-exec-tls
> 
> Disable the initial-exec TLS model for jemalloc's internal thread-local storage (on those platforms that support explicit settings). This can allow jemalloc to be dynamically loaded after program startup (e.g. using dlopen). Note that in this case, there will be two malloc implementations operating in the same process, which will almost certainly result in confusing runtime crashes if pointers leak from one implementation to the other.
>

**Comment by arnetheduck** [comment]
ok, I don't see why we shouldn't try this, but let's also update the readme to say that you need the `-dev` package as well to link

**Comment by arnetheduck** [comment]
per @yglukhov's comment in #10

**Comment by stefantalpalaru** [comment]
> let's also update the readme to say that you need the -dev package as well to link

Done.

**Comment by zah** [comment]
@arnetheduck, according to @yglukhov, using Sqlite is not an option right now, because the blockchain sync becomes slow enough to become practically unusable. There is a slight chance that the problem is caused by our inappropriate usage of the library somehow as the issue haven't been investigated very thoroughly yet.

**Pull request merged**
